# Generated by Django 4.1 on 2022-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body', models.TextField()),
                ('publish_date', models.DateField()),
                ('tags', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
    ]
